---
title: "Emelie’s Violins"
author: "Benjamin Moran"
date: "11/01/2018"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
```

```{r options, include=FALSE}
opts_chunk$set(echo = TRUE)
```

```{r data, echo = FALSE}
disc.dat1 <- read.delim("data/Discovery_time.txt", # fileloc
                        header = FALSE, # no header
                        col.names = "Seconds") # label the column
disc.dat1$Network = factor(c("Network 1")) # Add a column called 'Network' with the network name
disc.dat1$Seconds = disc.dat1$Seconds/1000 # convert to seconds

disc.dat2 <- data.frame("Seconds" = sample(10000:30000, 160, replace=T)) 
disc.dat2$Network = factor(c("Network 2")) # Add a column called 'Network' with the network name
disc.dat2$Seconds = disc.dat2$Seconds/1000 # convert to seconds
```

```{r combinedata, echo = FALSE}
data = rbind(disc.dat1, disc.dat2) # add each dataset here.
```

```{r getmedian, echo = FALSE}
med.data = data %>%
  group_by(Network) %>%
  summarise(Median = median(Seconds))
head(med.data)
```

```{r plot}
ggplot(data = data, aes(x = Network, y = Seconds, group = Network)) +
  theme_linedraw() + 
  geom_violin(position = "dodge", fill = "grey") + 
  geom_boxplot(width= 0.05, 
               outlier.colour = NA,
               position = "dodge", 
               fill = "black") +
  
  geom_point(data = med.data, aes(x = Network, y = Median),
             colour = "white") + 
  
  labs(y = "Time (seconds)", x = "Network")
  
```


